SOW = '▁'       # START OF WORD
MORPH_SEP = '+' # MORPH SEPARATOR
UNK = '<unk>'   # UNKNOWN
PAD = '<pad>'   # PADDING
SEG_SEP = "<seg>"
SOS = '<s>'
EOS = '</s>'
SEN_SEP = '<sep>'
RESERVERD_WORDS = [PAD, UNK, SOS, EOS] 